from .universidad_views import *
from .curso_views import *
from .tema_views import *
from .pregunta_views import *
from .examen_views import *
from .auth_views import *
from .admin_views import *
from .ajax_views import *
from .general_views import *
from .carga_masiva import *