# Generated by Django 5.1.5 on 2025-02-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='Preguntas.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(default=1)),
                ('nombre', models.CharField(blank=True, max_length=300)),
                ('contenido', models.FileField(upload_to='preguntas/')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.curso')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.tema')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Preguntas.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='Preguntas.universidad'),
        ),
    ]
