# Generated by Django 5.1.5 on 2025-02-11 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.FileField(upload_to='preguntas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
    ]
