# Generated by Django 5.2 on 2025-04-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0004_userprofile_alter_pregunta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.curso'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preguntas.userprofile'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='Preguntas.curso'),
        ),
    ]
