# Generated by Django 5.2 on 2025-04-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0005_alter_curso_universidad_alter_pregunta_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='universidad_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='curso_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='universidad_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tema',
            name='curso_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tema',
            name='universidad_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='curso',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.userprofile'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='Preguntas.curso'),
        ),
    ]
