# Generated by Django 5.2 on 2025-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0006_curso_universidad_nombre_pregunta_curso_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'universidad')},
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together={('nombre', 'curso')},
        ),
    ]
