# Generated by Django 5.1.5 on 2025-05-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0007_alter_universidad_nombre_alter_curso_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tema',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='curso_nombre',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tema_nombre',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='universidad_nombre',
        ),
        migrations.AlterField(
            model_name='curso',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.curso'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.tema'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Preguntas.userprofile'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='Preguntas.curso'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='universidad_nombre',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='curso_nombre',
        ),
        migrations.RemoveField(
            model_name='tema',
            name='universidad_nombre',
        ),
    ]
