# Generated by Django 5.1.5 on 2025-05-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0008_alter_curso_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='universidad',
        ),
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temas', to='Preguntas.curso'),
        ),
        migrations.CreateModel(
            name='CursoUniversidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universidades', to='Preguntas.curso')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_asignados', to='Preguntas.universidad')),
            ],
            options={
                'unique_together': {('universidad', 'curso')},
            },
        ),
    ]
