# Generated by Django 5.1.5 on 2025-05-04 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0009_remove_curso_universidad_alter_tema_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='universidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='Preguntas.universidad'),
        ),
        migrations.AlterField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temas', to='Preguntas.curso'),
        ),
        migrations.DeleteModel(
            name='CursoUniversidad',
        ),
    ]
