# Generated by Django 5.1.5 on 2025-05-17 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0011_remove_curso_universidad_universidad_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', help_text='Respuesta correcta (A, B, C, D o E)', max_length=1),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='contenido',
            field=models.FileField(help_text='Suba un archivo .doc o .docx con la pregunta', upload_to='preguntas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, help_text='Nivel de dificultad (por ejemplo: 1, 2, 3...)'),
        ),
    ]
