# Generated by Django 5.2.1 on 2025-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0012_pregunta_respuesta_alter_pregunta_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Supervisor'), ('admin', 'Admin'), ('user', 'User ')], default='user', max_length=20),
        ),
    ]
