# Generated by Django 5.2.1 on 2025-05-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Preguntas', '0014_examen_examenpregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tiene_solucion',
            field=models.BooleanField(default=False, help_text='Indica si la pregunta tiene solución'),
        ),
    ]
